### PR TITLE
add --tar-bin flag to garden-windows gdn args

### PR DESCRIPTION
**Pull request by sunjayBhatia**
- to support stream in/out
- the provided path is the default path for tar on the Windows stemcell

[#146150119]

### CODE REVIEW

**Comment by sunjayBhatia** [comment]
Hmmmm, looking again, the garden job doesn't expose these properties so maybe we can get away with just making them hard coded values in the job?

**Comment by teddyking** [comment]
Yeah I can't see a reason why these would need to be exposed via BOSH props. WDYT @julz?

**Comment by sunjayBhatia** [comment]
@teddyking well now that the nstar bin is coming from a different bosh release, does that leave more motivation to keep that BOSH property?

**Comment by sesmith177** [comment]
we've also added a max_containers bosh property to the job

**Comment by teddyking** [comment]
@sunjayBhatia good point - yes I'd say so. @sesmith177 out of interest what's the relevance of 75 being set as the default max?

**Comment by sunjayBhatia** [comment]
@teddyking @sesmith177 To put the context of our convo in here, it's sort of arbitrary and under the limit we saw when we ran gpats on windows with winc. We can evolve this value and change as needed when we do more experiments on limits

**Pull request merged**
