### PR TITLE
Ensure that the grootfs playground is clear and accessible.

### PR DESCRIPTION
**Pull request by andreas-kupries**
Origin ticket: cloudfoundry-incubator/kubecf#505 (Links to (semi-)related PRs).

### CODE REVIEW

**Comment by yulianedyalkova** [comment]
Hi @andreas-kupries, thanks for the PR!

Sadly I don't fully understand why you need this. We definitely do not want to delete and/or chmod all files in the grootfs store. Also, Garden does not know anything about a "playground" too.

**Comment by viovanov** [comment]
@yulianedyalkova we run this as part of kubecf, and grootfs data is stored on non-ephemeral storage, on PVCs, so we have to cleanup on restart, otherwise we'd see old data.
With BOSH, this should be a no-op on restart, because there would only be old data there, correct? If that's not the case, we could add a property named "cleanup_groot_data_on_start".

"playground" here simply means "data directory for grootfs" - we can update the comment

**Comment by andreas-kupries** [comment]
Thank you to @viovanov for the comment. I have translated this now into a comment in the script and pushed.

**Comment by viovanov** [comment]
ping @yulianedyalkova - does this make sense now?

**Pull request closed without merging**
